### ISSUE TITLE
[SWML Update] - `transparent_barge`

### ISSUE THREAD

**Issue by hey-august** [signalwire/docs-legacy#196]
Migrated from [#1038](https://github.com/signalwire/signalwire-docs/issues/1038) in the old repo. 

## Type Of Change

- [ ] New SWML Method
- [ ] Update to existing SWML Method

## Are These Changes Already In Production?

- [ ] Yes
- [ ] No

## Description
[Provide a detailed description of the changes]

- **Method(s) Added/Updated:**
  - Description of what was Added/Updated on the Method(s)
  - If this is a **New Method**, 
    - Provide a description of its purpose and functionality.
    - Provide what valid types it takes. 
- **Method Field(s) Added/Updated:**
  - Description of what Field was changed
  - If this is a **New Field**
    - Provide a description of its purpose and functionality.
    - Provide what valid types it takes.

## Context and Motivation
[Explain the context and the motivation behind these changes]

### SWML Example (Optional)
```yaml
version: 1.0.0
sections:
    main:
      - record_call:
          format: "wav"
          stereo: "true"
      - ai:
          post_prompt_url: https://cantina.signalwire.cloud/aicgi/post.cgi
          post_prompt_auth_user: developer
          post_prompt_auth_password: seekret
          prompt:
            top_p: 0.3
            temperature: 0.9
            text: >-
              You are Douglas, an AI natural language interface to the hitchhikers guide to the galaxy interactive game.

              Step 1. Introduce yourself
              Step 2. Ask the user what they want to do.
              Step 3. Without mentioning it to the user, pass the response to the game_control function unless they ask to reset the game then use the game_reset function instead. Never skip this step for any reason.
              Step 4. Tell the response from the game to the user.
              Step 5. Go back to step 2.
              
          post_prompt:
            text: Summarize the conversation
          params:
            attention_timeout: 10000
            attention_timeout_prompt: >-
              The user has not responded, say something british, brief, and humorously snarky to try to get their attention,
              when they respond, proceed to step 3. Say something different every time.
            end_of_speech_timeout: 250
            eleven_labs_stability: .50
            eleven_labs_similarity: .10
            transparent_barge: true
            conscience: "Always follow the steps exactly."
          languages:
            - name: English
              code: en-US
              voice: elevenlabs.fuN16f2J5BpaxSK63GVA
              fillers:
                - "very well,"
                - "right,"
                - "brilliant,"
                - "ok,"
                - "let's see,"
          SWAIG:
            defaults:
              web_hook_url: https://cantina.signalwire.cloud/aicgi/hhgg.cgi
              web_hook_auth_user: developer
              web_hook_auth_password: seekret
            functions:
              - function: hangup_hook
                purpose: call at end of the call
                argument: none
              - function: startup_hook
                purpose: call at beginning of the call
                argument: none                
              - function: game_control
                purpose: To send input to the game, The input should be expressed as a command suitable to a text adventure game in the imperative form (action first, followed by any specific objects or directions as needed)
                argument:
                  type: object
                  properties: 
                     input:
                       type: string
                       description: the message the user wants to send to the game
              - function: game_reset
                purpose: To reset the game when the user requests
```
