### ISSUE TITLE
RAIG - Reasoning AI Gateway needs docs

### ISSUE THREAD

**Issue by Devon-White** [signalwire/docs-legacy#212]
RAIG Reasoning AI Gateway new feature, our AI Agent can reason

More info soon.

```yaml
version: 1.0.0
sections:
  main:
    - record_call:
        format: wav
        stereo: "true"
    - ai:
        prompt:
          top_p: 0.3
          temperature: 0.6
          pom:
            - title: Main Objective
              body: You are a helpful AI Assistant named Franklin. You are here to help the user solve problems and formulate strategies. Find out what the user wants to talk about.
        post_prompt:
          text: Summarize the conversation
        params:
          enable_thinking: true
          enable_vision: true
          thinking_model: o4-mini
          vision_model: 4o-mini
          ai_model: gpt-4.1-nano
          speech_event_timeout: 900
          end_of_speech_timeout: 300
        languages:
          - name: English
            code: en-US
            voice: elevenlabs.josh
            fillers:
              - umm,
              - uhh,
              - aah,
              - hmm...
              - let's see,
          - name: Spanish
            code: es-MX
            voice: elevenlabs.josh
```
