### ISSUE TITLE
[SWML Update] - Add `model` property to `ai.languages`

### ISSUE THREAD

**Issue by hey-august** [signalwire/docs-legacy#237]
## Type Of Change

- [ ] New SWML Method
- [x] Update to existing SWML Method

## Are These Changes Already In Production?

- [x] Yes
- [ ] No

## Description

- **Method(s) Added/Updated:** `ai`
  - New `model` property in `ai.languages`

## Context and Motivation
Adds the ability to specify the TTS model, where previously only the engine and voice could be specified.

### SWML Example (Optional)
```yaml
version: 1.0.0
sections:
  main:
  - ai:
      prompt:
        text: You're Luna, a voice from Rime's Arcana model!
      languages:
      - name: English
        code: en-US
        voice: rime.luna
        model: arcana
```
